# Generated by Django 5.0 on 2024-12-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_food_rating_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
